FROM registry.fedoraproject.org/fedora-minimal:34

RUN microdnf install -y vsftpd && \
    microdnf clean all

COPY vsftpd.conf /etc/vsftpd/
COPY start_ftp_server.sh /bin/start_ftp_server.sh

RUN chmod +x /bin/start_ftp_server.sh && \
    mkdir /tmp/data

ENV USERNAME=datauser \
    PASSWORD=fuse

VOLUME /tmp/data

EXPOSE 20 21

CMD ["/bin/start_ftp_server.sh"]
