spec:
  template:
    spec:
      containers:
        - resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          readinessProbe:
            httpGet:
              # TODO: Change path
              path: /actuator/health/readinessState
              port: 8080
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /camel/
              port: 8080
            initialDelaySeconds: 30
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: TEMPERATURE_CELSIUS_SERVICE
            value: temperatures-celsius-service:3000


