FROM registry.access.redhat.com/ubi8/nodejs-16-minimal:1-10

# Install dependencies
COPY package.json package-lock.json /opt/app-root/src/
RUN npm ci --production

# Copy app
COPY . /opt/app-root/src/

EXPOSE 3000
ENTRYPOINT [ "npm", "start" ]
